# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios-extension'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'RubyMotionBlockerExtension'
  app.info_plist['NSExtension'] = {
    'NSExtensionPointIdentifier' => 'com.apple.Safari.content-blocker',
    'NSExtensionPrincipalClass' => 'ActionRequestHandler'
  }
end

